name: 'Crea il PDF degli appunti'
on: push
jobs:
  pdflatex:
    name: 'Compile LaTeX'
    runs-on: ubuntu-latest
    container: rekka/tectonic:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Run pdflatex'
        run: tectonic appunti.tex
      - name: 'Archive production artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: appunti
          path: appunti.pdf
